package biblioteca;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Consultar extends javax.swing.JFrame {

    private JFrame ventanaPrincipal;
    private File fichero; 

    
    public Consultar(JFrame vp, File fich) {
        this.fichero = fich;
        this.ventanaPrincipal = vp;
        this.ventanaPrincipal.setVisible(false);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        edtLimpiar = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldContraseña = new javax.swing.JTextField();
        edtAtras = new javax.swing.JButton();
        edtBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIBLIOTECA PICAZO");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Consulta Libro");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(159, 12, 175, 29);

        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Autor:");
        getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(12, 63, 86, 16);
        getContentPane().add(jTextFieldNombre);
        jTextFieldNombre.setBounds(129, 59, 254, 20);

        edtLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtLimpiar.setText("Limpiar");
        edtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(edtLimpiar);
        edtLimpiar.setBounds(306, 163, 77, 27);

        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Editorial:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(12, 91, 57, 16);

        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Serial:");
        getContentPane().add(jLabelContraseña);
        jLabelContraseña.setBounds(12, 125, 57, 16);
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(129, 89, 254, 20);

        jTextFieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldContraseña);
        jTextFieldContraseña.setBounds(129, 123, 254, 20);

        edtAtras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtAtras.setText("Atras");
        edtAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(edtAtras);
        edtAtras.setBounds(159, 163, 77, 27);

        edtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtBuscar.setText("Buscar");
        edtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(edtBuscar);
        edtBuscar.setBounds(16, 163, 75, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo ventana.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 470, 230);

        setSize(new java.awt.Dimension(492, 250));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtLimpiarActionPerformed
        jTextFieldNombre.setText("");
        jTextFieldUsuario.setText("");
        jTextFieldContraseña.setText("");
    }//GEN-LAST:event_edtLimpiarActionPerformed

    private void edtAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAtrasActionPerformed
        this.setVisible(false);
        ventanaPrincipal.setVisible(true);
    }//GEN-LAST:event_edtAtrasActionPerformed

    private void edtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtBuscarActionPerformed

        String espacios = " "; 
        String[] pedazos; 
        String nombre; 
        String nombrePedazo; 
        Boolean encontrado = false; 

        jTextFieldUsuario.setText("");
        jTextFieldContraseña.setText("");

        if (jTextFieldNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Te falta agregar el nombre", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                BufferedReader reader = new BufferedReader(new FileReader(fichero));  
                String linea = reader.readLine(); 

                if (linea == null) {
                    JOptionPane.showMessageDialog(this, "El archivo está vacio", "Archivo vacío", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    do {
                        pedazos = linea.split(espacios, 3); 

                        nombre = jTextFieldNombre.getText().toUpperCase();
                        nombrePedazo = pedazos[0].toUpperCase();
                        if (nombrePedazo.equals(nombre)) {
                            encontrado = true;
                            jTextFieldUsuario.setText(pedazos[1]);
                            jTextFieldContraseña.setText(pedazos[2]);
                        }
                        linea = reader.readLine(); 
                    } while (linea != null);
                    if (!encontrado) {
                        JOptionPane.showMessageDialog(this, "No hay coincidencia", "No encontrado", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                reader.close(); 
            } catch (IOException ex) {
                Logger.getLogger(Consultar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_edtBuscarActionPerformed

    private void jTextFieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContraseñaActionPerformed
    }//GEN-LAST:event_jTextFieldContraseñaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edtAtras;
    private javax.swing.JButton edtBuscar;
    private javax.swing.JButton edtLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField jTextFieldContraseña;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
