package biblioteca;

import biblioteca.Borrar;
import biblioteca.Consultar;
import biblioteca.Insertar;
import biblioteca.MenuPrincipal;
import java.io.File;
import javax.swing.JOptionPane;

public class editar extends javax.swing.JFrame {

    private MenuPrincipal menuP;
    private File archivo;

    public editar(MenuPrincipal mp, File archivo) {
        this.menuP = mp;
        this.archivo = archivo;
        this.menuP.setVisible(false);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtAñadir = new javax.swing.JButton();
        edtConsultar = new javax.swing.JButton();
        edtBorrar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIBLIOTECA PICAZO");
        setResizable(false);
        getContentPane().setLayout(null);

        edtAñadir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtAñadir.setText("Añadir");
        edtAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAñadirActionPerformed(evt);
            }
        });
        getContentPane().add(edtAñadir);
        edtAñadir.setBounds(20, 57, 91, 27);

        edtConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtConsultar.setText("Consultar");
        edtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(edtConsultar);
        edtConsultar.setBounds(129, 57, 92, 27);

        edtBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        edtBorrar.setText("Borrar");
        edtBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(edtBorrar);
        edtBorrar.setBounds(233, 57, 92, 27);

        jLabelTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Modificar");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(110, 10, 120, 29);

        menu.setText("Ir al Menú");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(20, 130, 89, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo ventana.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 370, 230);

        setSize(new java.awt.Dimension(386, 238));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed

        JOptionPane.showMessageDialog(this, "Regresar al menu", ";D", JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        menuP.setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void edtAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAñadirActionPerformed

        Insertar i = new Insertar(this, archivo);
    }//GEN-LAST:event_edtAñadirActionPerformed

    private void edtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtConsultarActionPerformed

        Consultar c = new Consultar(this, archivo);
    }//GEN-LAST:event_edtConsultarActionPerformed

    private void edtBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtBorrarActionPerformed

        Borrar b = new Borrar(this, archivo);
    }//GEN-LAST:event_edtBorrarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edtAñadir;
    private javax.swing.JButton edtBorrar;
    private javax.swing.JButton edtConsultar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JButton menu;
    // End of variables declaration//GEN-END:variables
}
